// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA_VRYXkSjIOtfLsAnVpTTjNgCyodgDzg',
    appId: '1:958194915753:web:b495d585382e6691094cb8',
    messagingSenderId: '958194915753',
    projectId: 'fyp-management-ce319',
    authDomain: 'fyp-management-ce319.firebaseapp.com',
    storageBucket: 'fyp-management-ce319.firebasestorage.app',
    measurementId: 'G-B0EBJL0707',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7EglUuzwD19NzqPItGaJu_IzGq1IQ-x0',
    appId: '1:958194915753:android:d003c5625deffa3f094cb8',
    messagingSenderId: '958194915753',
    projectId: 'fyp-management-ce319',
    storageBucket: 'fyp-management-ce319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2EGNlcH-EG4XvcBFwcXgBocAOKH4snI',
    appId: '1:958194915753:ios:cba5910acace3906094cb8',
    messagingSenderId: '958194915753',
    projectId: 'fyp-management-ce319',
    storageBucket: 'fyp-management-ce319.firebasestorage.app',
    iosBundleId: 'com.example.fypManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2EGNlcH-EG4XvcBFwcXgBocAOKH4snI',
    appId: '1:958194915753:ios:cba5910acace3906094cb8',
    messagingSenderId: '958194915753',
    projectId: 'fyp-management-ce319',
    storageBucket: 'fyp-management-ce319.firebasestorage.app',
    iosBundleId: 'com.example.fypManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA_VRYXkSjIOtfLsAnVpTTjNgCyodgDzg',
    appId: '1:958194915753:web:9e56ab9a169880df094cb8',
    messagingSenderId: '958194915753',
    projectId: 'fyp-management-ce319',
    authDomain: 'fyp-management-ce319.firebaseapp.com',
    storageBucket: 'fyp-management-ce319.firebasestorage.app',
    measurementId: 'G-7ZSBV0Z8VL',
  );
}
